### PR TITLE
Replace Fraction.js with BigNumber.js

### PR DESCRIPTION
**Pull request by saturn-network**
Closing #2 and #4

### CODE REVIEW

**Comment by saturn-network** [comment]
@PseudoDeterminist would you review please? Slightly refactored your ideas

**Comment by PseudoDeterminist** [comment]
Wow that looks much better than my commit. 

One question, one comment:

line 330

      return (await axios.get(gasApiUrl)).data * 1000000000

is doing a big multiplication on something. Probably at 'number' precision. I don't know what the data usually would look like, probably it's fine? But multiplication on 'number's bugs me.

Which brings me to my comment. This commit looks like a great start! Next thing, can we get rid of user expectation that they can use 'number's at all for token or ether amounts? Can they use string or BigNumber or BigNumberJS? Settling on string seems smart. As long as we have normal javascript numbers, we'll have worries and unpredictable issues we don't need. I'd like to see saturn.js almost never take a number as a function argument.

Thank you for fixing my idea up! This looks great to me!

**Comment by PseudoDeterminist** [comment]
Wow that looks much better than my commit. 

One question.

line 330

      return (await axios.get(gasApiUrl)).data * 1000000000

is doing a big multiplication on something. Probably at 'number' precision. I don't know what the data usually would look like, probably it's fine? But multiplication on 'number's bugs me.

Thank you for fixing my idea up! This looks great to me! I did go over every line of the new version. I cannot find anything else to ask about. I'm interested to find out about testing.

**Comment by PseudoDeterminist** [comment]
Wow that looks much better than my commit.

One question.

line 330

  return (await axios.get(gasApiUrl)).data * 1000000000

is doing a big multiplication on something. Probably at number precision. I don't know what the data usually would look like, probably it's fine? But multiplication on numbers bugs me. Accepting or returning numbers for crypto quantities bugs me.

Thank you for fixing my idea up! This looks great to me! I did go over every line of the new version. I cannot find anything else to ask about. I'm interested to find out about testing.

**Comment by PseudoDeterminist** [comment]
Wow that looks much better than my commit.

One question.

line 330

  return (await axios.get(gasApiUrl)).data * 1000000000

is doing a big multiplication on something, at number precision. I don't know what gas price data usually would look like, probably it's fine? But multiplication on numbers bugs me. Accepting or returning numbers for crypto quantities bugs me.

In fact, wherever we have (number | string) I want to ask why we even allow number.

But I get ahead of myself. Thank you for fixing my idea up! This looks great to me! I did go over every line of the new version. I cannot find anything else to ask about. I'm interested to find out about testing.

**Comment by PseudoDeterminist** [comment]
About priceMul and priceDiv:

I think this is where your modular division with remainder should be coming in.

When priceMul is price.shiftedBy(etherDecimals) and priceDiv is one.shiftedBy(decimals) then you can have

    priceMul = price.shiftedBy(etherDecimals - decimals)
    priceDiv = one

And no division is necessary.

But when

    priceDiv = price.shiftedBy(etherDecimals)
    priceMul = one.shiftedBy(decimals)

Here we should be doing modulo division with remainder in the smart contract.

I'd like to please see the Enceladus smart contract code. It is there that we will really get things right with doing division. And also it is there that we will prevent unsellable or unbuyable balances being introduced onto the exchange.

When we get Enceladus right, is when this attack vector will be really closed off.

**Comment by PseudoDeterminist** [comment]
About priceMul and priceDiv:

I think this is where your modular division with remainder should be coming in.

When priceMul is price.shiftedBy(etherDecimals) and priceDiv is one.shiftedBy(decimals) then you can have

    priceMul = price.shiftedBy(etherDecimals - decimals)
    priceDiv = one

And no division is necessary.

But when

    priceDiv = price.shiftedBy(etherDecimals)
    priceMul = one.shiftedBy(decimals)

Here we should be doing modulo division with remainder in the smart contract.

I'd like to please see the Enceladus smart contract code. It is there that we will really get things right with doing division. And also it is there that we will prevent unsellable or unbuyable balances being introduced onto the exchange.

In fact, with tokens, price and ethers all being represented as the correct integers, there will be no need to do things like (etherDecimals - decimals) et cetera at all.

See my example calculation earlier in this thread.

> If I begin writing my math in subunit integer form, I'll never call Fraction, or BigNumberWhatever.div, or .mul which is just as bad in the case of decimals past the decimal point. Just big integer math.

> Let's do that sell order for 171927 sam:

> 3295496000000000 wei - 687708000000000 wei = 2607788000000000 wei,

> another big beautiful round number that happens to exactly correspond to an order:

> 2607788000000000 wei / 4000000000 (wei / sam) = 651947 sam.

There will be a need for modulo division with remainder though. It answers the question:

    weiNeeded = tokensDesired.dividedToIntegerBy(price)
    weiToReturn = weiSent - weiNeeded

BigNumberJS.dividedToIntegerBy is actually modulo division. weiToReturn is the remainder.

I am betting Solidity has this method, and we should be using it.

To close off an attack vector, we need to be doing something like let Enceladus accept more wei or tokens than it needs and return the remainder. Then you can always sell or buy an order by sending more than enough, and everything is alright.

When we set up the correct BigNumber integer values, we do never need to separate priceMul and priceDiv. Only send price, as the correct integer, which will be what we are here calling price.shiftedBy(etherDecimals).

When we get Enceladus right, is when this attack vector will be really closed off.

**Comment by PseudoDeterminist** [comment]
Cross-posted to #5 

About priceMul and priceDiv:

I think this is where your modular division with remainder should be coming in.

When priceMul is price.shiftedBy(etherDecimals) and priceDiv is one.shiftedBy(decimals) then you can have

    priceMul = price.shiftedBy(etherDecimals - decimals)
    priceDiv = one

And no division is necessary.

But when

    priceDiv = price.shiftedBy(etherDecimals)
    priceMul = one.shiftedBy(decimals)

Here we should be doing modulo division with remainder in the smart contract, with

    priceDiv = price.shiftedBy(etherDecimals - decimals)
    priceMul = one

And here we see we never needed to send a fraction. Just the price to the right number of places.

In fact, with tokens, price and ethers all being represented as the correct integers, there will be no need to do things like (etherDecimals - decimals) et cetera at all.

See my example calculation earlier in this thread.

> If I begin writing my math in subunit integer form, I'll never call Fraction, or BigNumberWhatever.div, or .mul which is just as bad in the case of decimals past the decimal point. Just big integer math.
> 
> Let's do that sell order for 171927 sam:
> 
> 3295496000000000 wei - 687708000000000 wei = 2607788000000000 wei,
> 
> another big beautiful round number that happens to exactly correspond to an order:
> 
> 2607788000000000 wei / 4000000000 (wei / sam) = 651947 sam.

There will be a need for modulo division with remainder though. It answers the question:

    weiNeeded = tokensDesired.dividedToIntegerBy(price)
    weiToReturn = weiSent - weiNeeded

BigNumberJS.dividedToIntegerBy is actually modulo division. weiToReturn is the remainder.

I am betting Solidity has this method, and we should be using it.

To close off an attack vector, we need to be doing something like let Enceladus accept more wei or tokens than it needs and return the remainder. Then you can always sell or buy an order by sending more than enough, and everything is alright.

When we set up the correct BigNumber integer values, we do never need to separate priceMul and priceDiv. Only send price, as the correct integer, which will be what we are here calling price.shiftedBy(etherDecimals).

I'd like to please see the Enceladus smart contract code. It is there that we will really get things right with doing division. And also it is there that we will prevent unsellable or unbuyable balances being introduced onto the exchange.

When we get Enceladus right, is when this attack vector will be really closed off.

Until we get Enceladus right, any attacker with his own attacker.js interface that replaces our saturn.js, will be able to place orders that we cannot remove.

So can we look at Enceladus next? Or Saturn smart contract, whatever it is?

**Comment by PseudoDeterminist** [comment]
This comment will only apply to changes in at least one smart contract. So it's really a question. My previous comment stands with smart contracts as they are now.

About priceMul and priceDiv:

I think this is where your modular division with remainder should be coming in.

When priceMul is price.shiftedBy(etherDecimals) and priceDiv is one.shiftedBy(decimals) then you can have

    priceMul = price.shiftedBy(etherDecimals - decimals)
    priceDiv = one

And no division is necessary.

But when

    priceDiv = price.shiftedBy(etherDecimals)
    priceMul = one.shiftedBy(decimals)

Here we should be doing modulo division with remainder in the smart contract, with

    priceDiv = price.shiftedBy(etherDecimals - decimals)
    priceMul = one

And here we see we never needed to send a fraction. Just the price to the right number of places.

In fact, with tokens, price and ethers all being represented as the correct integers, there will be no need to do things like (etherDecimals - decimals) et cetera at all, except to get to and from human readable form. In saturn.js, we should immediately convert to the correct integers before doing calculations. Do our calculations, and send anything the smart contract needs in correct integer form. Then only convert back if we need to return results to a human.

See my example calculation from earlier in this thread:

> If I begin writing my math in subunit integer form, I'll never call Fraction, or BigNumberWhatever.div, or .mul which is just as bad in the case of decimals past the decimal point. Just big integer math.
> 
> Let's do that sell order for 171927 sam:
> 
> 3295496000000000 wei - 687708000000000 wei = 2607788000000000 wei,
> 
> another big beautiful round number that happens to exactly correspond to an order:
> 
> 2607788000000000 wei / 4000000000 (wei / sam) = 651947 sam.

There will be a need for modulo division with remainder though. It answers the question:

    tokensToBuy = weiSent.dividedToIntegerBy(price)
    weiNeeded = tokensToBuy.times(price)
    weiToReturn = weiSent - weiNeeded

BigNumberJS.dividedToIntegerBy is actually modulo division. weiToReturn is the remainder.

I am betting Solidity has this method, and we should be using it.

To close off an attack vector, we need to be doing something like let Enceladus accept more wei or tokens than it needs and return the remainder. Then you can always sell or buy an order by sending more than enough, and everything is alright.

When we set up the correct BigNumber integer values, we do never need to separate priceMul and priceDiv. Only send price, as the correct integer, which will be what we are here calling price.shiftedBy(etherDecimals).

I'd like to please see the Enceladus smart contract code. It is there that we will really get things right with doing division. And also it is there that we will prevent unsellable or unbuyable balances being introduced onto the exchange.

When we get Enceladus right, is when this attack vector will be really closed off.

Until we get Enceladus right, any attacker with his own attacker.js interface that replaces our saturn.js, will be able to place orders that we cannot remove.

So can we look at Enceladus next? Or Saturn smart contract, whatever it is?

**Comment by PseudoDeterminist** [comment]
Wow that looks much better than my commit! Thank you for fixing my idea up! This looks great to me!

I did go over every line of this new version. I cannot find anything else to ask about. I'm interested to find out about testing.

**Comment by saturn-network** [comment]
This time around manual testing will do. Going forward we should look into setting up automated tests. Will keep you updated on further progress.

Thank you for your diligence, perseverance and for finding `.shiftedBy`

**Comment by PseudoDeterminist** [comment]
Please also see PM at Telegram. Thanks!

**Comment by saturn-network** [comment]
Outstanding work

**Pull request merged**
